name 'chefo3'
maintainer 'Interwebs UG haftungsbeschränkt'
maintainer_email 'technik@interwebs-ug.de'
license 'MIT'
description 'Loads typo3 specific nginx config. Best used in conjunction with a vagrant dev environment.'
version '1.0.5'
depends 'nginx'
